The job is completed!
/usr/local/bin/python3: can't open file '/Users/Ian/Documents/GitHub/Data_project/WSB/populate_db.py': [Errno 2] No such file or directory
